"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.unsupportedPaths = exports.supportedPaths = exports.pathsAsGlobs = exports.pathsWithRegexAndEscapedChars = exports.pathsWithEscapedChars = exports.pathsWithRegex = void 0;
exports.pathsWithRegex = [
    "/(.*)",
    "/post/:slug(\\d{1,})",
    "/api-hello-regex/:first(.*)",
    "/unnamed-params/nested/(.*)/:test/(.*)",
    "/:path((?!another-page$).*)",
];
exports.pathsWithEscapedChars = [
    `/post\\(someStringBetweenParentheses\\)/:slug`,
    `/english\\(default\\)/:slug`,
];
exports.pathsWithRegexAndEscapedChars = [
    `/post/\\(escapedparentheses\\)/:slug(\\d{1,})`,
    `/post/\\(es\\?cap\\Wed\\*p\\{ar\\}en\\:th\\eses\\)`,
    `/post/\\(es\\?cap\\Wed\\*p\\{ar\\}en\\:th\\eses\\)/:slug(\\d{1,})`,
];
exports.pathsAsGlobs = [
    "/specific/:path*",
    "/another/:path*",
    "/about",
    "/",
    "/old-blog/:path*",
    "/blog/:path*",
    "/to-websocket",
    "/to-nowhere",
    "/rewriting-to-auto-export",
    "/rewriting-to-another-auto-export/:path*",
    "/to-another",
    "/another/one",
    "/nav",
    "/404",
    "/hello-world",
    "/static/hello.txt",
    "/another",
    "/multi-rewrites",
    "/first",
    "/hello",
    "/second",
    "/hello-again",
    "/to-hello",
    "/hello",
    "/blog/post-1",
    "/blog/post-2",
    "/test/:path",
    "/:path",
    "/test-overwrite/:something/:another",
    "/params/this-should-be-the-value",
    "/params/:something",
    "/with-params",
    "/query-rewrite/:section/:name",
    "/hidden/_next/:path*",
    "/_next/:path*",
    "/proxy-me/:path*",
    "/api-hello",
    "/api/hello",
    "/api-hello-param/:name",
    "/api-dynamic-param/:name",
    "/api/hello?name=:first*",
    "/api/hello?hello=:name",
    "/api/dynamic/:name?hello=:name",
    "/:path/post-321",
    "/with-params",
    "/with-params",
    "/catchall-rewrite/:path*",
    "/with-params",
    "/catchall-query/:path*",
    "/has-rewrite-1",
    "/has-rewrite-2",
    "/has-rewrite-3",
    "/has-rewrite-4",
    "/has-rewrite-5",
    "/:hasParam",
    "/has-rewrite-6",
    "/with-params",
    "/has-rewrite-7",
    "/has-rewrite-8",
    "/blog-catchall/:post",
    "/missing-rewrite-1",
    "/with-params",
    "/missing-rewrite-2",
    "/with-params",
    "/missing-rewrite-3",
    "/overridden/:path*",
];
exports.supportedPaths = [
    ...exports.pathsWithEscapedChars,
    ...exports.pathsAsGlobs,
    ...exports.pathsWithRegex,
    ...exports.pathsWithRegexAndEscapedChars,
];
exports.unsupportedPaths = [];
//# sourceMappingURL=paths.js.map